services:
  postgres:
    image: postgres:16
    container_name: pg_docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - pg_network
    ports:
      - 5433:${POSTGRES_PORT}

volumes:
  pg_volume:

networks:
  pg_network:
    external: true
    name: pg_network